# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel
